# Generated by Django 2.2 on 2020-04-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('socialdistancing', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifiaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=254)),
                ('user_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.UserProfile')),
            ],
        ),
    ]
